/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 thebridge2.glb 
*/

import React, { useEffect } from 'react'
import { useGLTF, useTexture } from '@react-three/drei'

export function bridge(props) {
  const matcapTexture = useTexture('/images/textures/mat1.png')
  const { nodes, materials } = useGLTF('/models/thebridge2.glb')

  useEffect(() => {
    Object.values(materials).forEach((m) => {
      if (m && m.isMeshStandardMaterial) {
        m.roughness = 0.95
        m.metalness = 0.0
        m.envMapIntensity = 0.2
        m.needsUpdate = true
      }
    })
  }, [materials])

  return (
    <group {...props} dispose={null}>
      <group position={[-3.044, 0.143, -3.428]} rotation={[Math.PI, -0.757, Math.PI]} scale={0.132}>
        <mesh geometry={nodes.Cylinder002_1.geometry} material={materials['Material.001']} castShadow receiveShadow/>
        <mesh geometry={nodes.Cylinder002_2.geometry} material={materials['Material.002']} castShadow receiveShadow/>
        <mesh geometry={nodes.Cylinder002_3.geometry} material={materials['Material.003']} castShadow receiveShadow/>
      </group>
      <group position={[-0.079, 0.677, 0.029]} scale={[0.648, 0.064, 0.047]}>
        <mesh geometry={nodes.Cube011_1.geometry} material={materials['Material.002']} castShadow receiveShadow/>
        <mesh geometry={nodes.Cube011_2.geometry} material={materials['Material.003']} castShadow receiveShadow/>
        <mesh geometry={nodes.Cube011_3.geometry} material={materials['Material.007']} castShadow receiveShadow/>
      </group>
      <group position={[1.166, 4.137, -3.148]} rotation={[-0.155, 0.015, -1.01]} scale={0.296}>
        <mesh geometry={nodes.Icosphere019.geometry} material={materials['Material.001']} castShadow receiveShadow/>
        <mesh geometry={nodes.Icosphere019_1.geometry} material={materials['Material.002']} castShadow receiveShadow/>
        <mesh geometry={nodes.Icosphere019_2.geometry} material={materials['Material.003']} castShadow receiveShadow/>
      </group>
      <group position={[4.694, 4.218, -4.119]} rotation={[0, -0.293, 0]} scale={0.141}>
        <mesh geometry={nodes.Cylinder001_1.geometry} material={materials['Material.001']} castShadow receiveShadow/>
        <mesh geometry={nodes.Cylinder001_2.geometry} material={materials['Material.002']} castShadow receiveShadow/>
        <mesh geometry={nodes.Cylinder001_3.geometry} material={materials['Material.003']} castShadow receiveShadow/>
      </group>
      <mesh geometry={nodes.Plane003.geometry} material={materials['Material.005']} position={[0, 1.067, 0]} scale={5.652} castShadow receiveShadow/>
      <group position={[-4.68, 5.009, 3.997]} rotation={[0, -1.546, 0]} scale={0.177}>
        <mesh geometry={nodes.Cylinder005_1.geometry} material={materials['Material.001']} castShadow receiveShadow/>
        <mesh geometry={nodes.Cylinder005_2.geometry} material={materials['Material.002']} castShadow receiveShadow/>
        <mesh geometry={nodes.Cylinder005_3.geometry} material={materials['Material.003']} castShadow receiveShadow/>
      </group>
      <group position={[-2.011, 3.267, -4.143]} rotation={[Math.PI, -0.076, Math.PI]} scale={0.17}>
        <mesh geometry={nodes.Cylinder006_1.geometry} material={materials['Material.001']} castShadow receiveShadow/>
        <mesh geometry={nodes.Cylinder006_2.geometry} material={materials['Material.002']} castShadow receiveShadow/>
      </group>
      <group position={[3.745, 2.731, -4.543]} rotation={[Math.PI, -0.076, Math.PI]} scale={0.132}>
        <mesh geometry={nodes.Cylinder007_1.geometry} material={materials['Material.001']} castShadow receiveShadow/>
        <mesh geometry={nodes.Cylinder007_2.geometry} material={materials['Material.002']} castShadow receiveShadow/>
      </group>
      <group position={[-4.464, 2.976, 2.497]} rotation={[Math.PI, -0.923, Math.PI]} scale={0.155}>
        <mesh geometry={nodes.Cylinder008_1.geometry} material={materials['Material.001']} castShadow receiveShadow/>
        <mesh geometry={nodes.Cylinder008_2.geometry} material={materials['Material.002']} castShadow receiveShadow/>
      </group>
      <group position={[-4.24, 2.484, 3.365]} rotation={[0, 0.356, 0]} scale={0.113}>
        <mesh geometry={nodes.Cylinder009_1.geometry} material={materials['Material.001']} castShadow receiveShadow/>
        <mesh geometry={nodes.Cylinder009_2.geometry} material={materials['Material.002']} castShadow receiveShadow/>
      </group>
      <group position={[2.739, 0.904, -4.04]} scale={[0.198, 0.316, 0.198]}>
        <mesh geometry={nodes.Circle_1.geometry} material={materials['Material.003']} castShadow receiveShadow/>
        <mesh geometry={nodes.Circle_2.geometry} material={materials['Material.010']} castShadow receiveShadow/>
      </group>
      <group position={[-4.683, 3.991, 5.514]} rotation={[-1.418, 0.349, 2.838]} scale={0.267}>
        <mesh geometry={nodes.Icosphere032.geometry} material={materials['Material.003']} castShadow receiveShadow/>
        <mesh geometry={nodes.Icosphere032_1.geometry} material={materials['Material.010']} castShadow receiveShadow/>
      </group>
      <mesh geometry={nodes.Icosphere018.geometry} material={materials['Material.003']} position={[4.324, 1.089, -3.447]} rotation={[Math.PI, -0.161, Math.PI]} scale={[0.459, 0.781, 0.459]} castShadow receiveShadow/>
      <mesh geometry={nodes.Icosphere017.geometry} material={materials['Material.003']} position={[-4.005, 1.089, -4.098]} rotation={[Math.PI, -1.11, Math.PI]} scale={[0.527, 0.896, 0.527]} castShadow receiveShadow/>
      <mesh geometry={nodes.Circle001.geometry} material={materials['Material.011']} position={[-1.073, 1.071, 3.14]} rotation={[0, 0.599, 0]} scale={0.306} castShadow receiveShadow/>
      <mesh geometry={nodes.Circle002.geometry} material={materials['Material.011']} position={[-1.581, 1.071, 2.728]} rotation={[-Math.PI, 1.181, -Math.PI]} scale={0.306} castShadow receiveShadow/>
      <mesh geometry={nodes.Circle003.geometry} material={materials['Material.011']} position={[-0.298, 1.071, 3.4]} rotation={[0, -1.044, 0]} scale={0.254} castShadow receiveShadow/>
      <mesh geometry={nodes.Circle004.geometry} material={materials['Material.011']} position={[-0.443, 1.071, 2.608]} rotation={[-Math.PI, 0.191, -Math.PI]} scale={0.343} castShadow receiveShadow/>
      <mesh geometry={nodes.Circle005.geometry} material={materials['Material.011']} position={[-1.111, 1.071, 2.728]} rotation={[Math.PI, -0.717, Math.PI]} scale={0.306} castShadow receiveShadow/>
      <mesh geometry={nodes.Circle006.geometry} material={materials['Material.011']} position={[-0.581, 1.071, 2.953]} rotation={[Math.PI, -1.447, Math.PI]} scale={0.248} castShadow receiveShadow/>
      <mesh geometry={nodes.Circle007.geometry} material={materials['Material.011']} position={[0.795, 1.071, -2.708]} rotation={[-Math.PI, 1.127, -Math.PI]} scale={0.306} castShadow receiveShadow/>
      <mesh geometry={nodes.Circle008.geometry} material={materials['Material.011']} position={[-0.205, 1.071, -2.523]} rotation={[Math.PI, -0.235, Math.PI]} scale={0.306} castShadow receiveShadow/>
      <mesh geometry={nodes.Circle009.geometry} material={materials['Material.011']} position={[1.172, 1.071, -3.174]} rotation={[0, 0.372, 0]} scale={0.254} castShadow receiveShadow/>
      <mesh geometry={nodes.Circle010.geometry} material={materials['Material.011']} position={[0.367, 1.071, -3.153]} rotation={[Math.PI, -1.225, Math.PI]} scale={0.343} castShadow receiveShadow/>
      <mesh geometry={nodes.Circle011.geometry} material={materials['Material.011']} position={[0.383, 1.071, -2.64]} rotation={[0, -1.009, 0]} scale={0.306} castShadow receiveShadow/>
      <mesh geometry={nodes.Circle012.geometry} material={materials['Material.011']} position={[0.732, 1.071, -3.277]} rotation={[0, 1.264, 0]} scale={0.248} castShadow receiveShadow/>
      <mesh geometry={nodes.Circle013.geometry} material={materials['Material.011']} position={[1.128, 1.071, -2.523]} rotation={[Math.PI, -1.142, Math.PI]} scale={0.26} castShadow receiveShadow/>
      <mesh geometry={nodes.Circle014.geometry} material={materials['Material.011']} position={[-1.111, 1.071, 1.396]} rotation={[Math.PI, -0.717, Math.PI]} scale={0.399} castShadow receiveShadow/>
      <mesh geometry={nodes.Succulent.geometry} material={materials['Material.012']} position={[-1.143, 1.077, 2.983]} rotation={[2.424, 0.387, -2.823]} scale={[-0.023, -0.115, -0.023]} castShadow receiveShadow/>
      <mesh geometry={nodes.Succulent001.geometry} material={materials['Material.012']} position={[-1.263, 1.08, 1.344]} rotation={[1.229, -0.868, 1.134]} scale={[-0.026, -0.13, -0.026]} castShadow receiveShadow/>
      <mesh geometry={nodes.Succulent002.geometry} material={materials['Material.012']} position={[-0.266, 1.077, 2.983]} rotation={[0.709, -0.363, 0.296]} scale={[-0.027, -0.137, -0.027]} castShadow receiveShadow/>
      <mesh geometry={nodes.Succulent003.geometry} material={materials['Material.012']} position={[0.411, 1.08, -2.645]} rotation={[0.862, -0.64, 0.608]} scale={[-0.033, -0.166, -0.033]} castShadow receiveShadow/>
      <mesh geometry={nodes.Succulent004.geometry} material={materials['Material.012']} position={[0.965, 1.08, -3.085]} rotation={[0.666, 0.169, -0.131]} scale={[-0.023, -0.119, -0.023]} castShadow receiveShadow/>
      <mesh geometry={nodes.Succulent005.geometry} material={materials['Material.012']} position={[1.102, 1.08, -2.604]} rotation={[0.856, 0.633, -0.598]} scale={[-0.019, -0.094, -0.019]} castShadow receiveShadow/>
      <group position={[-0.963, 3.731, -4.629]} rotation={[-2.984, -0.195, 2.16]} scale={0.203}>
        <mesh geometry={nodes.Icosphere041.geometry} material={materials['Material.001']} castShadow receiveShadow/>
        <mesh geometry={nodes.Icosphere041_1.geometry} material={materials['Material.002']} castShadow receiveShadow/>
        <mesh geometry={nodes.Icosphere041_2.geometry} material={materials['Material.003']} castShadow receiveShadow/>
      </group>
      <mesh geometry={nodes.Plane001.geometry} material={materials['Material.009']} position={[3.744, 1.132, 0.071]} rotation={[Math.PI, -1.382, Math.PI]} scale={0.375} castShadow receiveShadow/>
      <mesh geometry={nodes.Plane002.geometry} material={materials['Material.009']} position={[4.072, 1.132, -0.572]} rotation={[0, -0.255, 0]} scale={0.327} castShadow receiveShadow/>
      <mesh geometry={nodes.Plane004.geometry} material={materials['Material.009']} position={[4.371, 1.132, -0.051]} rotation={[-Math.PI, 0.139, -Math.PI]} scale={0.298} castShadow receiveShadow/>
      <mesh geometry={nodes.Plane005.geometry} material={materials['Material.009']} position={[4.176, 1.132, 0.299]} rotation={[Math.PI, -1.092, Math.PI]} scale={0.245} castShadow receiveShadow/>
      <mesh geometry={nodes.Plane006.geometry} material={materials['Material.009']} position={[4.558, 1.132, 0.299]} rotation={[0, -1.146, 0]} scale={0.212} castShadow receiveShadow/>
      <mesh geometry={nodes.Plane007.geometry} material={materials['Material.009']} position={[-3.852, 1.132, -0.281]} rotation={[-Math.PI, 1.549, -Math.PI]} scale={0.375} castShadow receiveShadow/>
      <mesh geometry={nodes.Plane008.geometry} material={materials['Material.009']} position={[-4.037, 1.132, 0.416]} rotation={[-Math.PI, 0.044, -Math.PI]} scale={0.327} castShadow receiveShadow/>
      <mesh geometry={nodes.Plane009.geometry} material={materials['Material.009']} position={[-4.439, 1.132, -0.031]} rotation={[0, 0.072, 0]} scale={0.298} castShadow receiveShadow/>
      <mesh geometry={nodes.Plane010.geometry} material={materials['Material.009']} position={[-4.321, 1.132, -0.414]} rotation={[0, 1.303, 0]} scale={0.245} castShadow receiveShadow/>
      <mesh geometry={nodes.Plane011.geometry} material={materials['Material.009']} position={[-4.696, 1.132, -0.334]} rotation={[-Math.PI, 0.934, -Math.PI]} scale={0.212} castShadow receiveShadow/>
      <mesh geometry={nodes.Cube009.geometry} material={materials['Material.003']} position={[4.167, 0.934, -2.494]} rotation={[-Math.PI, -0.316, -2.943]} scale={[0.007, 0.005, 0.003]} castShadow receiveShadow/>
      <mesh geometry={nodes.Cube002.geometry} material={materials['Material.003']} position={[3.332, 0.987, -2.854]} rotation={[-Math.PI, 0.876, -2.943]} scale={[0.007, 0.005, 0.003]} castShadow receiveShadow/>
      <mesh geometry={nodes.Cube003.geometry} material={materials['Material.003']} position={[3.42, 1.055, 1.252]} rotation={[0, 0.411, -2.943]} scale={[-0.006, -0.004, -0.004]} castShadow receiveShadow/>
      <mesh geometry={nodes.Cube006.geometry} material={materials['Material.003']} position={[-3.671, 1.034, -2.783]} rotation={[-Math.PI, -0.55, -2.943]} scale={[0.006, 0.004, 0.002]} castShadow receiveShadow/>
      <mesh geometry={nodes.Cube007.geometry} material={materials['Material.003']} position={[-4.647, 0.982, -2.96]} rotation={[Math.PI, 0.443, -2.943]} scale={[0.006, 0.004, 0.002]} castShadow receiveShadow/>
      <mesh geometry={nodes.Cube008.geometry} material={materials['Material.003']} position={[-1.429, 1.034, -2.783]} rotation={[Math.PI, 0.301, -2.943]} scale={[0.005, 0.003, 0.002]} castShadow receiveShadow/>
      <mesh geometry={nodes.Cube010.geometry} material={materials['Material.003']} position={[-3.862, 0.985, 2.774]} rotation={[0, -1.195, 0.199]} scale={[0.006, 0.004, 0.004]} castShadow receiveShadow/>
      <mesh geometry={nodes.Cube011.geometry} material={materials['Material.003']} position={[-3.979, 1.029, 3.479]} rotation={[-Math.PI, -0.755, -2.943]} scale={[0.008, 0.004, 0.003]} castShadow receiveShadow/>
      <mesh geometry={nodes.Cube012.geometry} material={materials['Material.003']} position={[-3.955, 1.029, 4.349]} rotation={[0, 0.311, 0.199]} scale={[0.006, 0.004, 0.003]} castShadow receiveShadow/>
      <mesh geometry={nodes.Cube013.geometry} material={materials['Material.003']} position={[0.083, 1.01, 4.528]} rotation={[-Math.PI, -0.417, -2.943]} scale={[0.007, 0.003, 0.002]} castShadow receiveShadow/>
      <group position={[-0.133, 0.556, 0.125]} scale={[5.394, 0.178, 5.146]}>
        <mesh geometry={nodes.Cube019.geometry} material={materials['Material.009']} castShadow receiveShadow/>
        <mesh geometry={nodes.Cube019_1.geometry} material={materials['Material.016']} castShadow receiveShadow/>
        <mesh geometry={nodes.Cube019_2.geometry} material={materials['Material.008']} castShadow receiveShadow/>
      </group>
      <mesh geometry={nodes.Icosphere002.geometry} material={materials['Material.003']} position={[-2.783, 1.089, 4.213]} rotation={[0, -0.82, 0]} scale={[0.365, 0.621, 0.365]} castShadow receiveShadow/>
      
      {/* Lantern 1 */}
      <group position={[1.639, 5.793, -1.771]} rotation={[0, 0.89, 0]} scale={0.072}>
        <mesh geometry={nodes.Cylinder010_1.geometry} material={materials['Material.002']} />
        <mesh geometry={nodes.Cylinder010_2.geometry} material={materials['Material.006']} />
        <mesh geometry={nodes.Cylinder010_3.geometry} material={materials['Material.004']} />

        {/* Glow sphere */}
        <mesh>
          <sphereGeometry args={[0.15, 16, 16]} />
          <meshStandardMaterial
            color="#fff7cc"
            emissive="#ffeb99"
            emissiveIntensity={3}
          />
        </mesh>

        {/* Light emission */}
        <pointLight
          intensity={1.67}
          distance={5}
          decay={2}
          color="#ffeb99"
        />
      </group>

      {/* Lantern 2 */}
      <group position={[-2.04, 5.389, 0.861]} rotation={[0, 1.18, 0]} scale={0.072}>
        <mesh geometry={nodes.Cylinder011_1.geometry} material={materials['Material.002']} />
        <mesh geometry={nodes.Cylinder011_2.geometry} material={materials['Material.006']} />
        <mesh geometry={nodes.Cylinder011_3.geometry} material={materials['Material.004']} />

        <mesh>
          <sphereGeometry args={[0.15, 16, 16]} />
          <meshStandardMaterial color="#fff7cc" emissive="#ffeb99" emissiveIntensity={3} />
        </mesh>

        <pointLight intensity={0.67} distance={4} decay={2} color="#ffeb99" />
      </group>

      {/* Lantern 3 */}
      <group position={[0.002, 6.558, 0.43]} rotation={[0, 1.18, 0]} scale={0.072}>
        <mesh geometry={nodes.Cylinder012_1.geometry} material={materials['Material.002']} />
        <mesh geometry={nodes.Cylinder012_2.geometry} material={materials['Material.006']} />
        <mesh geometry={nodes.Cylinder012_3.geometry} material={materials['Material.004']} />

        <mesh>
          <sphereGeometry args={[0.15, 16, 16]} />
          <meshStandardMaterial color="#fff7cc" emissive="#ffeb99" emissiveIntensity={3} />
        </mesh>

        <pointLight intensity={0.67} distance={4} decay={2} color="#ffeb99" />
      </group>

      {/* Lantern 4 */}
      <group position={[-1.835, 1.304, 1.51]} scale={0.072}>
        <mesh geometry={nodes.Cylinder013_1.geometry} material={materials['Material.002']} />
        <mesh geometry={nodes.Cylinder013_2.geometry} material={materials['Material.006']} />
        <mesh geometry={nodes.Cylinder013_3.geometry} material={materials['Material.004']} />

        <mesh>
          <sphereGeometry args={[0.15, 16, 16]} />
          <meshStandardMaterial color="#fff7cc" emissive="#ffeb99" emissiveIntensity={3} />
        </mesh>

        <pointLight intensity={.08} distance={4} decay={4.25} color="#ffeb99" />
      </group>

      {/* Lantern 5 */}
      <group position={[-0.114, 1.304, 2.114]} scale={0.072}>
        <mesh geometry={nodes.Cylinder014.geometry} material={materials['Material.002']} />
        <mesh geometry={nodes.Cylinder014_1.geometry} material={materials['Material.006']} />
        <mesh geometry={nodes.Cylinder014_2.geometry} material={materials['Material.004']} />

        <mesh>
          <sphereGeometry args={[0.15, 16, 16]} />
          <meshStandardMaterial color="#fff7cc" emissive="#ffeb99" emissiveIntensity={3} />
        </mesh>

        <pointLight intensity={.067} distance={4} decay={4} color="#ffeb99" />
      </group>

      {/* Lantern 6 */}
      <group position={[-1.438, 3.449, -1.069]} scale={0.072}>
        <mesh geometry={nodes.Cylinder003_1.geometry} material={materials['Material.002']} />
        <mesh geometry={nodes.Cylinder003_2.geometry} material={materials['Material.006']} />
        <mesh geometry={nodes.Cylinder003_3.geometry} material={materials['Material.004']} />
        <mesh>
          <sphereGeometry args={[0.15, 16, 16]} />
          <meshStandardMaterial color="#fff7cc" emissive="#ffeb99" emissiveIntensity={3} />
        </mesh>
        <pointLight intensity={1} distance={4} decay={2} color="#ffeb99" />
      </group>
    </group>
  )
}

useGLTF.preload('/models/thebridge2.glb')
